DROP TABLE Products; 
CREATE TABLE Products (
    id INT primary key,  /* id la khóa chính*/
    name NVARCHAR(100),
    price FLOAT check (price>=0),
    stock INT check (stock>=0),
	type NVARCHAR(100),
    season NVARCHAR(100)
);
INSERT INTO Products (id, name, price, stock, type, season) VALUES (1, N'Hoa Hồng Đỏ', 15000, 100, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (2, N'Hoa Cúc Vàng', 10000, 80, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (3, N'Hoa Ly Trắng', 20000, 60, N'Hoa tươi', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (4, N'Hoa Hồng Xanh', 22000, 50, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (5, N'Hoa Sen Hồng', 18000, 70, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (6, N'Hoa Cẩm Tú Cầu', 17000, 40, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (7, N'Hoa Mẫu Đơn', 25000, 45, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (8, N'Hoa Lan Hồ Điệp', 30000, 30, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (9, N'Hoa Tulip Đỏ', 23000, 55, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (10, N'Hoa Cẩm Chướng', 12000, 75, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (11, N'Hoa Hướng Dương', 16000, 85, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (12, N'Hoa Thạch Thảo', 9000, 90, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (13, N'Hoa Lưu Ly', 11000, 95, N'Hoa khô', N'Đông');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (14, N'Hoa Dã Quỳ', 14000, 100, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (15, N'Hoa Tigon', 10500, 65, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (16, N'Hoa Đào', 20000, 50, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (17, N'Hoa Mai', 25000, 30, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (18, N'Hoa Giấy', 8000, 120, N'Hoa khô', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (19, N'Hoa Baby', 9500, 110, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (20, N'Hoa Phăng', 15500, 75, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (21, N'Hoa Oải Hương', 17000, 60, N'Hoa khô', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (22, N'Hoa Cát Tường', 14500, 70, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (23, N'Hoa Tử Đằng', 19500, 50, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (24, N'Hoa Ban', 13000, 80, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (25, N'Hoa Ngọc Lan', 14000, 75, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (26, N'Hoa Thiên Điểu', 27000, 40, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (27, N'Hoa Xuyến Chi', 9500, 95, N'Hoa dại', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (28, N'Hoa Sứ', 17500, 55, N'Hoa chậu', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (29, N'Hoa Ngọc Thảo', 16000, 60, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (30, N'Hoa Cúc Họa Mi', 10000, 90, N'Hoa tươi', N'Đông');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (31, N'Hoa Cẩm Tú Cầu Xanh', 18500, 45, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (32, N'Hoa Hồng Nhung', 16500, 85, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (33, N'Hoa Lài', 9500, 100, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (34, N'Hoa Cát Đằng', 15000, 70, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (35, N'Hoa Bướm', 12000, 80, N'Hoa dại', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (36, N'Hoa Tigon Hồng', 11000, 75, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (37, N'Hoa Lan Rừng', 32000, 35, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (38, N'Hoa Móng Cọp', 14500, 50, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (39, N'Hoa Cỏ May', 8000, 120, N'Hoa dại', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (40, N'Hoa Nguyệt Quế', 18000, 65, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (41, N'Hoa Hồng Tím', 19000, 55, N'Hoa tươi', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (42, N'Hoa Thược Dược', 17000, 75, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (43, N'Hoa Cẩm Nhung', 15000, 60, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (44, N'Hoa Lan Chuỗi Ngọc', 28000, 30, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (45, N'Hoa Lồng Đèn', 16000, 85, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (46, N'Hoa Mắt Nai', 9500, 100, N'Hoa dại', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (47, N'Hoa Cúc Vạn Thọ', 12500, 90, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (48, N'Hoa Sống Đời', 10000, 110, N'Hoa chậu', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (49, N'Hoa Thiên Lý', 13500, 70, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (50, N'Hoa Cẩm Quỳ', 14500, 80, N'Hoa dại', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (51, N'Hoa Phong Lữ', 16000, 60, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (52, N'Hoa Trà My', 18000, 70, N'Hoa tươi', N'Đông');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (53, N'Hoa Cẩm Tú Tròn', 17000, 55, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (54, N'Hoa Lan Vũ Nữ', 29000, 35, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (55, N'Hoa Hồng Bạch', 15000, 80, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (56, N'Hoa Bách Hợp', 24000, 45, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (57, N'Hoa Cúc Tím', 13000, 90, N'Hoa tươi', N'Đông');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (58, N'Hoa Mười Giờ', 9000, 100, N'Hoa chậu', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (59, N'Hoa Quỳnh', 20000, 30, N'Hoa tươi', N'Đêm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (60, N'Hoa Dâm Bụt', 11000, 85, N'Hoa dại', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (61, N'Hoa Chuông', 14500, 70, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (62, N'Hoa Sao Nháy', 10500, 95, N'Hoa dại', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (63, N'Hoa Lồng Đèn Nhật', 17000, 60, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (64, N'Hoa Hồng Trắng', 15000, 75, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (65, N'Hoa Hồng Cam', 15500, 85, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (66, N'Hoa Hồng Vàng', 16000, 90, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (67, N'Hoa Hồng Đen', 22000, 40, N'Hoa tươi', N'Đặc biệt');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (68, N'Hoa Cúc Đại Đóa', 12000, 95, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (69, N'Hoa Ngũ Sắc', 10000, 100, N'Hoa dại', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (70, N'Hoa Chiều Tím', 9500, 85, N'Hoa dại', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (71, N'Hoa Mai Tứ Quý', 25000, 40, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (72, N'Hoa Súng', 13500, 55, N'Hoa nước', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (73, N'Hoa Thủy Tiên', 18000, 70, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (74, N'Hoa Dạ Yến Thảo', 15500, 80, N'Hoa chậu', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (75, N'Hoa Sử Quân Tử', 14500, 65, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (76, N'Hoa Tóc Tiên', 11000, 90, N'Hoa chậu', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (77, N'Hoa Cúc Mâm Xôi', 14000, 100, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (78, N'Hoa Hồng Cổ', 19500, 50, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (79, N'Hoa Lan Dạ Hương', 27000, 35, N'Hoa lan', N'Đông');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (80, N'Hoa Hồng Juliet', 32000, 25, N'Hoa nhập khẩu', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (81, N'Hoa Tulip Vàng', 23000, 60, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (82, N'Hoa Tulip Tím', 24000, 50, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (83, N'Hoa Lavender Khô', 18000, 80, N'Hoa khô', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (84, N'Hoa Cúc Xuxi', 12500, 90, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (85, N'Hoa Vân Anh', 15000, 65, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (86, N'Hoa Hải Đường', 17000, 60, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (87, N'Hoa Lan Kiếm', 26000, 30, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (88, N'Hoa Kim Ngân', 14000, 85, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (89, N'Hoa Sứ Thái', 15000, 100, N'Hoa chậu', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (90, N'Hoa Lan Phi Điệp', 31000, 25, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (91, N'Hoa Mận Trắng', 19000, 45, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (92, N'Hoa Sim', 13000, 80, N'Hoa dại', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (93, N'Hoa Lan Tỏi', 16000, 60, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (94, N'Hoa Cẩm Tú Cầu Tím', 17500, 70, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (95, N'Hoa Lan Mokara', 28000, 40, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (96, N'Hoa Mai Chiếu Thủy', 13500, 85, N'Hoa chậu', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (97, N'Hoa Tường Vi', 15000, 75, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (98, N'Hoa Cúc Mẫu Đơn', 15500, 90, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (99, N'Hoa Thủy Chung', 14500, 65, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (100, N'Hoa Bướm Đêm', 16000, 55, N'Hoa dại', N'Quanh năm');
