DROP TABLE IF EXISTS Products; 
CREATE TABLE Products (
    id INT primary key,  /* id la khóa chính*/
    name NVARCHAR(100) NOT NULL,
    price FLOAT NOT NULL check (price>=0), /* giá phải >=0**/
    stock INT NOT NULL check (stock>=0), /* tồn kho >=0*/
	type NVARCHAR(100) NOT NULL,
    season NVARCHAR(100) NOT NULL,
	UNIQUE(name, type) /* không trùng tên và loại sản phẩm*/
);
INSERT INTO Products (id, name, price, stock, type, season) VALUES (1, N'Hoa Hồng Đỏ', 150000, 100, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (2, N'Hoa Cúc Vàng', 200000, 80, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (3, N'Hoa Ly Trắng', 80000, 60, N'Hoa tươi', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (4, N'Hoa Hồng Xanh', 120000, 50, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (5, N'Hoa Sen Hồng', 250000, 70, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (6, N'Hoa Cẩm Tú Cầu', 90000, 40, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (7, N'Hoa Mẫu Đơn', 50000, 45, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (8, N'Hoa Lan Hồ Điệp', 180000, 30, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (9, N'Hoa Tulip Đỏ', 220000, 55, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (10, N'Hoa Cẩm Chướng', 95000, 75, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (11, N'Hoa Hướng Dương', 110000, 85, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (12, N'Hoa Thạch Thảo', 130000, 90, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (13, N'Hoa Lưu Ly', 170000, 95, N'Hoa khô', N'Đông');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (14, N'Hoa Dã Quỳ', 160000, 100, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (15, N'Hoa Tigon', 55000, 65, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (16, N'Hoa Đào', 140000, 50, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (17, N'Hoa Mai', 200000, 30, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (18, N'Hoa Giấy', 60000, 120, N'Hoa khô', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (19, N'Hoa Baby', 180000, 110, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (20, N'Hoa Phăng', 210000, 75, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (21, N'Hoa Oải Hương', 160000, 60, N'Hoa khô', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (22, N'Hoa Cát Tường', 230000, 70, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (23, N'Hoa Tử Đằng', 120000, 50, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (24, N'Hoa Ban',  95000, 80, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (25, N'Hoa Ngọc Lan', 45000, 75, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (26, N'Hoa Thiên Điểu', 140000, 40, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (27, N'Hoa Xuyến Chi', 75000, 95, N'Hoa dại', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (28, N'Hoa Sứ', 100000, 55, N'Hoa chậu', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (29, N'Hoa Ngọc Thảo', 80000, 60, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (30, N'Hoa Cúc Họa Mi', 80000, 90, N'Hoa tươi', N'Đông');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (31, N'Hoa Cẩm Tú Cầu Xanh', 110000, 45, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (32, N'Hoa Hồng Nhung', 130000, 85, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (33, N'Hoa Lài', 70000, 100, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (34, N'Hoa Cát Đằng', 90000, 70, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (35, N'Hoa Bướm', 60000, 80, N'Hoa dại', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (36, N'Hoa Tigon Hồng', 100000, 75, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (37, N'Hoa Lan Rừng', 95000, 35, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (38, N'Hoa Móng Cọp', 85000, 50, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (39, N'Hoa Cỏ May', 190000, 120, N'Hoa dại', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (40, N'Hoa Nguyệt Quế', 65000, 65, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (41, N'Hoa Hồng Tím', 120000, 55, N'Hoa tươi', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (42, N'Hoa Thược Dược', 85000, 75, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (43, N'Hoa Cẩm Nhung', 130000, 60, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (44, N'Hoa Lan Chuỗi Ngọc', 170000, 30, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (45, N'Hoa Lồng Đèn', 150000, 85, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (46, N'Hoa Mắt Nai', 70000, 100, N'Hoa dại', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (47, N'Hoa Cúc Vạn Thọ', 85000, 90, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (48, N'Hoa Sống Đời', 50000, 110, N'Hoa chậu', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (49, N'Hoa Thiên Lý', 120000, 70, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (50, N'Hoa Cẩm Quỳ', 250000, 80, N'Hoa dại', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (51, N'Hoa Phong Lữ', 150000, 60, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (52, N'Hoa Trà My', 180000, 70, N'Hoa tươi', N'Đông');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (53, N'Hoa Cẩm Tú Tròn', 170000, 55, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (54, N'Hoa Lan Vũ Nữ', 290000, 35, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (55, N'Hoa Hồng Bạch', 150000, 80, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (56, N'Hoa Bách Hợp', 240000, 45, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (57, N'Hoa Cúc Tím', 130000, 90, N'Hoa tươi', N'Đông');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (58, N'Hoa Mười Giờ', 90000, 100, N'Hoa chậu', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (59, N'Hoa Quỳnh', 200000, 30, N'Hoa tươi', N'Đêm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (60, N'Hoa Dâm Bụt', 110000, 85, N'Hoa dại', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (61, N'Hoa Chuông', 145000, 70, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (62, N'Hoa Sao Nháy', 105000, 95, N'Hoa dại', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (63, N'Hoa Lồng Đèn Nhật', 170000, 60, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (64, N'Hoa Hồng Trắng', 150000, 75, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (65, N'Hoa Hồng Cam', 155000, 85, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (66, N'Hoa Hồng Vàng', 160000, 90, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (67, N'Hoa Hồng Đen', 220000, 40, N'Hoa tươi', N'Đặc biệt');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (68, N'Hoa Cúc Đại Đóa', 120000, 95, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (69, N'Hoa Ngũ Sắc', 100000, 100, N'Hoa dại', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (70, N'Hoa Chiều Tím', 95000, 85, N'Hoa dại', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (71, N'Hoa Mai Tứ Quý', 250000, 40, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (72, N'Hoa Súng', 135000, 55, N'Hoa nước', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (73, N'Hoa Thủy Tiên', 180000, 70, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (74, N'Hoa Dạ Yến Thảo', 155000, 80, N'Hoa chậu', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (75, N'Hoa Sử Quân Tử', 145000, 65, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (76, N'Hoa Tóc Tiên', 110000, 90, N'Hoa chậu', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (77, N'Hoa Cúc Mâm Xôi', 140000, 100, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (78, N'Hoa Hồng Cổ', 195000, 50, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (79, N'Hoa Lan Dạ Hương', 270000, 35, N'Hoa lan', N'Đông');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (80, N'Hoa Hồng Juliet', 320000, 25, N'Hoa nhập khẩu', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (81, N'Hoa Tulip Vàng', 230000, 60, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (82, N'Hoa Tulip Tím', 240000, 50, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (83, N'Hoa Lavender Khô', 180000, 80, N'Hoa khô', N'Quanh năm');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (84, N'Hoa Cúc Xuxi', 125000, 90, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (85, N'Hoa Vân Anh', 150000, 65, N'Hoa tươi', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (86, N'Hoa Hải Đường', 170000, 60, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (87, N'Hoa Lan Kiếm', 260000, 30, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (88, N'Hoa Kim Ngân', 140000, 85, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (89, N'Hoa Sứ Thái', 150000, 100, N'Hoa chậu', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (90, N'Hoa Lan Phi Điệp', 310000, 25, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (91, N'Hoa Mận Trắng', 190000, 45, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (92, N'Hoa Sim', 130000, 80, N'Hoa dại', N'Thu');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (93, N'Hoa Lan Tỏi', 160000, 60, N'Hoa leo', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (94, N'Hoa Cẩm Tú Cầu Tím', 175000, 70, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (95, N'Hoa Lan Mokara', 280000, 40, N'Hoa lan', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (96, N'Hoa Mai Chiếu Thủy', 135000, 85, N'Hoa chậu', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (97, N'Hoa Tường Vi', 150000, 75, N'Hoa tươi', N'Hè');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (98, N'Hoa Cúc Mẫu Đơn', 155000, 90, N'Hoa Tết', N'Tết');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (99, N'Hoa Thủy Chung', 145000, 65, N'Hoa tươi', N'Xuân');
INSERT INTO Products (id, name, price, stock, type, season) VALUES (100, N'Hoa Bướm Đêm', 160000, 55, N'Hoa dại', N'Quanh năm');
